markdown: kramdown

title: Covid-19 in New York City

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE
  - boro
  - deaths
  - Geography-resources
  - recent
  - testing